name: Build Rocky ISO with Kickstart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y --no-install-recommends genisoimage xorriso curl p7zip-full

      # Step 3: Download Rocky Linux ISO
      - name: Download Rocky ISO
        run: |
          curl -L -o rocky.iso https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9-latest-x86_64-minimal.iso

      # Step 4: Extract ISO contents
      - name: Extract ISO
        run: |
          mkdir -p iso_contents
          7z x rocky.iso -o./iso_contents || echo "Extraction failed"

      # Step 5: Debug - Verify kernel and initrd files
      - name: Verify Kernel and Initrd
        run: |
          ls -l iso_contents/isolinux/vmlinuz
          ls -l iso_contents/isolinux/initrd.img
          file iso_contents/isolinux/vmlinuz
          file iso_contents/isolinux/initrd.img

      # Step 6: Inject boot.msg, ks.cfg, and isolinux.cfg
      - name: Inject Custom Files
        run: |
          cp boot.msg iso_contents/boot.msg
          cp ks.cfg iso_contents/ks.cfg
          cp isolinux.cfg iso_contents/isolinux/isolinux.cfg

      # Step 7: Rebuild the ISO
      - name: Build Custom ISO
        run: |
          xorriso -as mkisofs \
            -o custom-rocky.iso \
            -b isolinux/isolinux.bin \
            -c isolinux/boot.cat \
            -no-emul-boot \
            -boot-load-size 4 \
            -boot-info-table \
            -eltorito-alt-boot \
            -e images/efiboot.img \
            -no-emul-boot \
            -V "Custom_Rocky_9.3" \
            -r -J -joliet-long \
            iso_contents/

      # Step 8: Upload the ISO as an artifact
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-rocky-iso
          path: custom-rocky.iso
